#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm

from dataclasses import dataclass

import fire

from utils.plot_utils import text_to_list
from utils.plot_utils import get_colors_colorbar, adjust_lightness
from utils.plot_utils import aestheticfig


scatter_style = {'jet': {'alpha': .5},
                 'ghosts': {'alpha': .1},
                 'particles' : {}}
color_scale = {'jet': .5, 'ghosts': .7, 'particles': 1}


def eta_to_theta(eta_val):
    """Returns the polar angle for a pseudorapidity eta_val."""
    return 2.*np.arctan(np.exp(-eta_val))

def ptyphis_to_ptthetaphis(pjs):
    """Returns the pt/theta/phi vals for a set of input
    pt/y/phi values.

    Assumes that y is approximately theta."""
    new_pjs = []

    if isinstance(pjs[0], list) or isinstance(pjs[0], np.ndarray):
        for pj in pjs:
            new_pjs.append(np.array(
                [pj[0], eta_to_theta(pj[1]), pj[2]]))
    else:
        new_pjs = [pjs[0], eta_to_theta(pjs[1]), pjs[2]]

    return np.array(new_pjs)


def yphi_distance(pj1, pj2):
    """Distance in the rapidity-azimuth plane
    between two pseudojets, in the format used
    in this file.
    """
    return np.sqrt((pj1[1]-pj2[1])**2 + (pj1[2]-pj1[2])**2)


def mod_shift(val, shift_val, mod_val):
    """Shifts a value val by a shift shift_val, mod mod_val"""
    val += shift_val
    while val > mod_val:
        val -= mod_val
    return val


def data_to_spherepoints_weights(pjs, r=1.):
    """Takes a list of pt/theta/phi values and returns
    associated weights and points on the sphere (with radius 1)
    """
    spherepoints = []
    weights = []
    
    if isinstance(pjs[0], list) or isinstance(pjs[0], np.ndarray):
        for pj in pjs:
            weights.append(pj[0])
            x = r * np.cos(pj[2]) * np.sin(pj[1]) 
            y = r * np.sin(pj[2]) * np.sin(pj[1])
            z = r * np.cos(pj[1])
            spherepoints.append(np.array([x, y, z]))
    else:
        weights = [pjs[0]]
        x = r * np.cos(pjs[2]) * np.sin(pjs[1]) 
        y = r * np.sin(pjs[2]) * np.sin(pjs[1])
        z = r * np.cos(pjs[1])
        spherepoints = [[x, y, z]]

    return spherepoints, np.array(weights)


def near(p, point_list, d0, weights):
    """For spherical visualization, below.
    Find an effective weight of points
    p' within point_list for which p' is
    nearer to p than d0.
    """
    total_weight = 0
    
    for i, point in enumerate(point_list):
        weight = weights[i]
        dist = np.linalg.norm(p - point)
        if dist < d0:
            total_weight += weight * (1 - dist/d0)

    return total_weight


@dataclass
class EventVisualizer:
    # File from which to read
    filename : str = None

    # Event properties
    event_dict = None
    total_pt: float = None
    has_particles : bool = False
    # Event plotting properties
    max_rap: float = None
    min_rap: float = None
    max_phi: float = None
    min_phi: float = None

    # Jet properties
    radius: float = None
    close_jet_inds = None 

    # Figures
    phi_shift: float = 0
    scatter_ax = None
    ax_3d = None


    def read_file(self):
        """Reads and stores event data from self.filename."""
        # Reading event from self.filename
        event, kwargs = text_to_list(self.filename,
                            None,                       # all columns
                            lambda x:float(x[1]) > 0,   # rows with pt>0
                            'radius')                   # find radius
        self.radius = float(kwargs['radius'])

        # Finding number of jets and establishing a colorbar for
        # visualizing hardest jets as red, softest as blue
        jet_inds = [part[4] for part in event]
        self.num_jets = np.max(np.array(jet_inds).astype(int))
        self.colors, _ = get_colors_colorbar(range(self.num_jets))
        self.colors = self.colors[::-1]

        # Initializing event information
        self.event_dict = {}
        self.total_pt = 0
        self.close_jet_inds = []

        # ---------------------------------
        # Storing information for each jet
        # ---------------------------------
        for ijet in np.arange(1, self.num_jets+1):
            self.event_dict[ijet] = {}

            # Jet info
            jet = [np.array(part[1:4]).astype(np.float64)
                   for part in event
                   if part[0] == 'J' and int(part[4]) == ijet][0]
            self.event_dict[ijet]['jet'] = jet
            self.total_pt += jet[0]

            # Particle info
            particles = np.array(([np.array(part[1:4]).astype(np.float64)
                          for part in event
                          if part[0] == 'P' and int(part[4]) == ijet]))
            self.event_dict[ijet]['particles'] = particles

            # Ghost info
            ghosts = np.array(([np.array(part[1:4]).astype(np.float64)
                       for part in event if part[0] == 'G' and int(part[4]) == ijet]))
            self.event_dict[ijet]['ghosts'] = ghosts

            # Marking jets closer together than the jet radius
            for jjet in self.event_dict.keys():
                if jjet >= ijet: break
                if yphi_distance(self.event_dict[ijet]['jet'],
                        self.event_dict[jjet]['jet']) < self.radius/10:
                    [self.close_jet_inds.append(ind)
                     for ind in [ijet, jjet]]
            
        self.has_particles = True
        self.close_jet_inds = np.unique(self.close_jet_inds)

        return


    def set_yphi_lims(self, max_rap="use_event", min_rap="use_event",
                      max_phi="use_event", min_phi="use_event"):
        """Sets the boundaries for the visualization plots."""
        # - - - - - - - - - - - - - - - - -
        # Setting plot params based on event info
        # - - - - - - - - - - - - - - - - -
        # Find an appropriate plot boundaries for the event, if we are asked
        if any([a == "use_event" for a in [max_rap, min_rap, max_phi, min_phi]]):
            assert self.has_particles,\
                "No event to use for setting plot boundaries."
                # Problem if we want to use the event but have no particles

            max_raps = []
            min_raps = []
            max_phis = []
            min_phis = []
            max_shift_phis = []
            min_shift_phis = []

            for ijet in np.arange(1, self.num_jets+1):
                for pjs in [self.event_dict[ijet]['ghosts'],
                            self.event_dict[ijet]['particles']]:
                    # Ghosts should subsume particles, but considering both
                    # makes bugs easier to catch and is more generalizable.
                    if len(pjs) > 0:
                        max_raps.append(np.max([pj[1] for pj in pjs]))
                        min_raps.append(np.min([pj[1] for pj in pjs]))
                        max_phis.append(np.max([pj[2] for pj in pjs]))
                        min_phis.append(np.min([pj[2] for pj in pjs]))

                        shifted_phis = [mod_shift(pj[2], np.pi, 2.*np.pi)
                                        for pj in pjs]
                        max_shift_phis.append(np.max(shifted_phis))
                        min_shift_phis.append(np.min(shifted_phis))

            # Setting global plot params
            if max_rap == "use_event":
                self.max_rap = np.max(max_raps)
            if min_rap == "use_event":
                self.min_rap = np.min(min_raps)

            if max_phi == "use_event" or self.min_phi == "use_event":
                # Checking if shifted angles make the plot more compact
                angle_diff = np.max(max_phis) - np.min(min_phis)
                angle_shift_diff = np.max(max_shift_phis) - np.min(min_shift_phis)

                if angle_shift_diff < angle_diff:
                    # If they do, shift all angles
                    max_phi = np.max(max_shift_phis)
                    min_phi = np.min(min_shift_phis)

                    self.phi_shift = np.pi

                    for ijet in np.arange(1, self.num_jets+1):
                        for pj_type, pjs in self.event_dict[ijet].items():
                            if pj_type == "jet":
                                pjs[2] = mod_shift(pjs[2], np.pi, 2.*np.pi)
                            else:
                                for pj in pjs:
                                    pj[2] = mod_shift(pj[2], np.pi, 2.*np.pi)

                else:
                    max_phi = np.max(max_phis)
                    min_phi = np.min(min_phis)

                self.max_phi = max_phi
                self.min_phi = min_phi

        # - - - - - - - - - - - - - - - - -
        # Setting any given boundaries 
        # - - - - - - - - - - - - - - - - -
        if max_rap is not None and max_rap != "use_event":
            self.max_rap = max_rap
        if min_rap is not None and min_rap != "use_event":
            self.min_rap = min_rap
        if max_phi is not None and max_phi != "use_event":
            self.max_phi = max_phi
        if min_phi is not None and min_phi != "use_event":
            self.min_phi = min_phi
        
        return
 

    def scatter_vis(self, pj_type=['ghosts', 'jet', 'particles']):
        """Visualizes the event stored in self.event_dict as a scatter plot.
        Includes particles, jets, and ghosts (jet areas) by default.
        """
        if not self.has_particles:
            self.read_file()
            self.set_yphi_lims()

        if self.scatter_ax is None:
            _, self.scatter_ax = plt.subplots()
            self.scatter_ax.set_title("Event Visualization")
            self.scatter_ax.set_xlabel(r"Rapidity ($y$)")
            if self.phi_shift == 0:
                self.scatter_ax.set_ylabel(r"Azimuthal Angle ($\phi$)")
            elif self.phi_shift == np.pi:
                self.scatter_ax.set_ylabel("Azimuthal Angle "+\
                                           r"($\phi - \pi$)")
            else:
                self.scatter_ax.set_ylabel("Azimuthal Angle "+\
                                           r"($\phi$"+f"-{self.phi_shift})")
            self.scatter_ax.set_xlim(self.min_rap, self.max_rap)
            self.scatter_ax.set_ylim(self.min_phi, self.max_phi)
            
            self.scatter_ax.set_aspect((self.max_rap-self.min_rap)
                                       /(self.max_phi-self.min_phi))

        if isinstance(pj_type, list):
            # Default: Plot ghosts (background), then jets,
            # then particles (foreground)
            for pj_cat in pj_type:
                self.scatter_vis(pj_cat)
            plt.show()

        else:
            # Plotting the given type of data
            if pj_type == 'jet':
                print(f"Marking jets closer than {self.radius/10 = }"
                      +" with a translucent red 'X'.")
            for i in range(self.num_jets):
                color = self.colors[i]
                ijet = i+1
                pj_data = np.transpose(
                    self.event_dict[ijet][pj_type])
                if len(pj_data) > 0:
                    pts, ys, phis = pj_data[0], pj_data[1], pj_data[2]
                    if pj_type == 'particles':
                        s = pts*5
                    elif pj_type == 'jet':
                        s = pts*20
                    elif pj_type == 'ghosts':
                        s = np.ones(len(pts))*10
                    else:
                        raise AssertionError(f"Invalid {pj_type = }")
                        s = pts

                    self.scatter_ax.scatter(ys, phis, s=s,
                        color=adjust_lightness(color, color_scale[pj_type]),
                        **scatter_style[pj_type])
                    if pj_type == 'jet' and ijet in self.close_jet_inds:
                        self.scatter_ax.scatter(ys, phis, s=750, alpha=.2,
                                                color='r', marker='X',
                                                zorder=5)


    def sphere_vis(self):
        """
        https://stackoverflow.com/a/52964926
        https://stackoverflow.com/questions/22128909/plotting-the-temperature-distribution-on-a-sphere-with-python
        """
        if not self.has_particles:
            self.read_file()

        # Event analysis
        event_data = []

        for ijet in np.arange(1, self.num_jets+1):
            pjs = self.event_dict[ijet]['particles']
            num_particles = len(ptyphis_to_ptthetaphis(pjs))
            if ijet == 1:
                event_data = ptyphis_to_ptthetaphis(pjs)
            else:
                event_data = np.concatenate((event_data,
                                ptyphis_to_ptthetaphis(pjs)))
        point_list, pts = data_to_spherepoints_weights(event_data)

        # Event visualization on the sphere
        fig = plt.figure()
        ax = fig.add_subplot( 1, 1, 1, projection='3d')

        u = np.linspace(0, 2 * np.pi, 120)
        v = np.linspace(0, np.pi, 60)

        # create the sphere surface
        XX = 1 * np.outer(np.cos(u), np.sin(v))
        YY = 1 * np.outer(np.sin(u), np.sin(v))
        ZZ = 1 * np.outer(np.ones(np.size(u)), np.cos(v))

        WW = XX.copy()
        for i in range( len( XX ) ):
            for j in range( len( XX[0] ) ):
                x = XX[ i, j ]
                y = YY[ i, j ]
                z = ZZ[ i, j ]
                WW[ i, j ] = near(np.array([x, y, z ]), point_list, .1, pts)
        WW = WW / np.amax( WW )
        myheatmap = WW

        ax.plot_surface(XX, YY,  ZZ, cstride=1, rstride=1,
                        facecolors=cm.jet(myheatmap))
        plt.axis('off')
        plt.grid(visible=None)

        plt.show() 

    def vis_3d(self, pj_type=None):
        # Set up figure
        if self.ax_3d is None:
            fig = plt.figure()
            self.ax_3d = fig.add_subplot(111, projection='3d')
            self.ax_3d.set_title("Event Visualization")
            self.ax_3d.set_xlabel(r"Rapidity ($y$)")
            self.ax_3d.set_ylabel(r"Azimuthal Angle ($\phi$)")
            self.ax_3d.set_xlim(-np.pi, np.pi)
            self.ax_3d.set_ylim(0, 2.*np.pi)

        if pj_type is not None:
            for i in range(2): #self.num_jets):
                color = self.colors[i]
                ijet = i+1
                pj_data = np.transpose(
                    self.event_dict[ijet][pj_type])
                if len(pj_data) > 0:
                    pts, ys, phis = pj_data[0], pj_data[1], pj_data[2]

                    hist, y_edges, phi_edges = np.histogram2d(ys, phis,
                                                              bins=(1000,1000),
                                                              weights=pts)
                    y_pos, phi_pos = np.meshgrid(y_edges[:-1]+y_edges[1:],
                                                 phi_edges[:-1]+phi_edges[1:])

                    y_pos = y_pos.flatten()/2.
                    phi_pos = phi_pos.flatten()/2.
                    hist_pos = np.zeros_like (y_pos)

                    dy = y_edges[1] - y_edges[0]
                    dphi = phi_edges[1] - phi_edges[0]
                    dz = hist.flatten()

                    self.ax_3d.bar3d(y_pos, phi_pos, hist_pos, dy, dphi, dz,
                                     color=color, zsort='average')

        else:
            for pj_cat in ['ghosts', 'particles']:
                self.vis_3d(pj_cat)


if __name__ == "__main__":
    fire.Fire(EventVisualizer)
