#!/usr/bin/env bash
# Script for quick visualization
# Example usage:
# ./scripts/vis_events_narrow.sh -l hadron -p qcd -j akt -s ca -R 2 -r 1

# Writing an event
./write_tools/write_ewocs --write_event narrow_emissions --write_ewocs false $@ -n 100
# Note: default looks at the first 10 events generated by pythia, but adding the option
#       ```-n [N]```
#       will visualize the first N events

# write_ewocs stores a pointer to the filename with event info in another file...
value=`cat event_vis_pointer.txt`
echo "Visualizing events stored at "$value

# Visualizing
chmod +x event_vis_script.sh
./event_vis_script.sh

echo "Erasing the evidence >:)"
rm $value
rm event_vis_pointer.txt
rm event_vis_script.sh
